### ISSUE TITLE
Can't swap AE to FST and AE to SND using mob browser and app

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/dex-ui#347]
Can't swap AE to FST and AE to SND :
![2022-06-07 6 57 33 пп](https://user-images.githubusercontent.com/69896204/172427658-b3950513-7cad-4bc8-8122-9190df00ef9d.jpg)

**Comment by kenodressel** [comment]
blocked until testnet is running again and

**Comment by kenodressel** [comment]
@Liubov-crypto could you please test again?

**Comment by Liubov-crypto** [comment]
For some reason, I couldn't connect to the DEX properly. I tried several times but the DEX only worked on the mainnet even though the wallet was switched to the testnet.
![photo_2022-07-14 16 39 25](https://user-images.githubusercontent.com/69896204/178995888-b178dcdd-9730-48e9-b930-82589e79b083.jpeg)


I used for tests wallet: commit 8b85da9 / v.0.9.9 and browser: Safari ver. 15.5

**Comment by bogdan-manole** [comment]
- it worked for me around 2 times, but the wallet is opening new tab in Safari.
- after that it is doing the same as reported above

**Comment by kenodressel** [comment]
We checked and it seems like the wallet was signing the requests against the wrong network. This should be fixed with the new release.
