### ISSUE TITLE
Update SDK to the 13 version

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/dex-ui#357]
@ifaouibadi is taking some time to research on deeplinks with this version, then we will upgrade the dex-ui

**Comment by kenodressel** [comment]
Lets postpone this for now. Until @bogdan-manole verifies the call data issue

**Comment by marc0olo** [comment]
just for tracking this the calldata topic -> https://github.com/aeternity/aepp-calldata-js/issues/155

**Comment by kenodressel** [comment]
Lets wait until the SDK is updated to the new calldata lib

**Comment by kenodressel** [comment]
Lets move to 13 instead :)
