### ISSUE TITLE
Import Pool for AE/SND on testnet result in error

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/dex-ui#363]
`Cannot read properties of null (reading 'ct_7tTzPfvv3Vx8pCEcuk1kmgtn4sFsYCQDzLi1LvFs8T5PJqgsC|ct_JDp175ruWd7mQggeHewSLS1PFXt9AzThCDaFedxon8mF8xTRF')`

**Comment by bogdan-manole** [comment]
@CedrikNikita 

I can't reproduce it 

<img width="750" alt="image" src="https://user-images.githubusercontent.com/3176255/178326289-a2f2f40e-a096-4dbe-87a5-aa3478e4fb70.png">
