### ISSUE TITLE
Inform the user when swap doesn't have real chance to execute

### ISSUE THREAD

**Issue by bogdan-manole** [aeternity/dex-ui#373]
### Is your feature request related to a problem?

The actual ratio between tokenA and tokenB is calculated not just by the ratio between liquidityA and liquidityB, but also by the price impact over that liquidity.
It would be nice if the user will be informed when swapping transaction has little to no changes of execution due to the low slippage 

### Describe the solution you would like to have.

It would be nice if the user will be informed to increase his slippage when the app knows there are few chances for the swap transaction to succeed with the current slippage

### Anything else you want us to know?

I will attach the drawing board we had in the discussion with @kenodressel 

![Untitled-2022-07-01-1128](https://user-images.githubusercontent.com/3176255/176906428-7d319a4b-fdc5-492c-b237-4f77badd9919.png)

**Comment by kenodressel** [comment]
similar to this but in yellow:
![image](https://user-images.githubusercontent.com/765921/178681325-11c302b3-4440-4356-b725-2e82143330db.png)
