### ISSUE TITLE
You need to scroll through all tokens to select a different token view list

### ISSUE THREAD

**Issue by ErkanKanden** [aeternity/dex-ui#379]
### Is your feature request related to a problem?

Currently the default view for tokens to select on https://aepp.dex.superhero.com/swap under "Manage Token Lists" is the "Superhero DEX Selection". Once I change to "AE Middleware List", I can finally see all validated AEX-9 token contracts, but I have to scroll all the way down through all tokens in order to be able to get to "Manage Token Lists" again. 

### Describe the solution you would like to have.

There should be a shortcut or some symbol to always get to this view without having to scroll or search for it.

**Comment by bogdan-manole** [comment]
"Manage token list" button position is designed to be fixed on the tokens-selection view, though it seems if the screen vertical is too small the button goes below the bottom of the screen

<img width="350" alt="image" src="https://user-images.githubusercontent.com/3176255/177194891-5725d3a7-ab6d-4fcb-ad9c-d91deb337cc5.png"> <img width="380" alt="image" src="https://user-images.githubusercontent.com/3176255/177195002-764ecb0d-5ac9-4ee7-a5c4-500a2b4bb512.png">

**Comment by ErkanKanden** [comment]
Would be great if it could be fixed on all screen sizes
