### ISSUE TITLE
Add Fields to each AEX-9 Token with Middleware data such as number of Token Holders and Transactions

### ISSUE THREAD

**Issue by ErkanKanden** [aeternity/dex-ui#381]
### Is your feature request related to a problem?

Community members have issued the following problems: 

"would be helpful to have a bit more info in the swap token interface to help determine which of the tokens/contracts with the same name, like ABC for example, is the actual token"

"What are the "Superhero DEX Selection 2 tokens".. the lists are a bit confusing. Would be good if we could view the tokens in the list."

"Personally, I am all for providing links/tools/data to empower users"

"From a user experience perspective it's just unclear (currently) from the lists what is what. There are about 10-15 ABC tokens for example and so I'm not sure which is what and from the list there doesn't seem to be any kind of identifying or qualifying information available."

"I think infrastructure specific tokens like WAE is totally fine to indentify in the DEX. Info people need."

"I'm really excited about the DEX. It's monumental. I want to use it any way I can. I want to throw tokens at it, play with it"

"Trying to swap AE to WAE and seeing "Internal error: tx_nonce_too_high_for_account" "

### Describe the solution you would like to have.

Provide links/tools/data to empower users to take investment decisions. Ideally we should at least have the same level of information as https://www.aeknow.org/token for the manually vetted tokens.

**Comment by ErkanKanden** [comment]
"Peace is reason, [04.07.2022, 18:11:27]:
Maybe adding a contract id or something along with the token name? Some other identifying piece of info that can be cross-checked by users against aeknow.org"

"owner wallet address would be good"

**Comment by kenodressel** [comment]
I think this is a bit more complex to tackle. Additional information about the contracts is covered by #308
