### ISSUE TITLE
Add liquidity option Token stuck

### ISSUE THREAD

**Issue by Lfh2msn** [aeternity/dex-ui#388]
### What happened?

 Adding liquidity option token causes browser warning:
`Property undefined was accessed during render but is not defined on instance. `

The warning loops infinitely until the browser crashes。

justify-content: flex-end;
At the same time, some places use justify-content: **end**;
This will bring a warning, it is recommended to modify to **flex-end**

### How can we reproduce it?

Mac platform or mobile device, 
chrome or firefox browser,
dex-ui latest version, 
click pool, 
add token

### mobile

Both

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

**Comment by bogdan-manole** [comment]
@Lfh2msn could you please provide more details? 
I can't get any of those issues described above

**Comment by kenodressel** [comment]
@Lfh2msn any update? Otherwise we close this ticket :)
