### ISSUE TITLE
Sometimes  Add Liquidity, the ratio is the opposite

### ISSUE THREAD

**Issue by barceguo** [aeternity/dex-ui#401]
### What happened?

![捕获](https://user-images.githubusercontent.com/31126684/178994922-67d98c5b-b332-4145-9cf2-e9b872be63cb.JPG)

### How can we reproduce it?

Add Liquidity

### mobile

Desktop

### What browsers are you seeing the problem on?

Chrome

**Comment by kenodressel** [comment]
already solved by #395
