### ISSUE TITLE
deployment url doesn't use listed tokens from the dex-backend

### ISSUE THREAD

**Issue by bogdan-manole** [aeternity/dex-ui#429]
### What happened?

The same branch is built and used locally vs a deployment URL behaves differently.
The deployed dex doesn't use the listed tokens from the dex-backend

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/3176255/181488964-f1798df7-892b-46e7-9bfd-0473ef150a39.png">

### How can we reproduce it?

use any PR , build it locally and compare it with the ployment url

### mobile

Both

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by kenodressel** [comment]
Neither does the local setup for me :see_no_evil: Do we still have the WTT token listed in the backend?

**Comment by bogdan-manole** [comment]
> Neither does the local setup for me 🙈 Do we still have the WTT token listed in the backend?

yup, is still there:
https://dex-backend-mainnet.prd.aepps.com/tokens/listed

**Comment by kenodressel** [comment]
According to @CedrikNikita it is intended behavior. We should reverse that.

**Comment by kenodressel** [comment]
reverse this: https://github.com/aeternity/dex-ui/commit/f5a210ad81e5d8c5d4936585f40662d7bd0afe9e
