### ISSUE TITLE
Can't connect web wallet and DEX

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/dex-ui#434]
### What happened?

Can't connect web wallet and DEX. After connecting, dex works on the mainnet, although the wallet is on the testnet:
![sh and dex](https://user-images.githubusercontent.com/69896204/181783482-90c651f1-d35d-46db-b410-76cde5697e0f.png)
![mainnet ](https://user-images.githubusercontent.com/69896204/181783453-36517520-f971-4f92-8a02-b6def7b1aa08.png)

### How can we reproduce it?

1. Open wallet.superhero.com and switch to the testnet
2. Go to https://dex.prd.aepps.com/swap
3. Click on Connect Wallet
4. See the error
5. Click on Open my Wallet
6. Click on connect with dex on the wallet pop-up
7. See that the dex is on the mainnet after the connection with the wallet 

### mobile

Desktop

### What browsers are you seeing the problem on?

Chrome

**Comment by kenodressel** [comment]
Could you try to clean your cache?

**Comment by Liubov-crypto** [comment]
> Could you try to clean your cache?

Every time before I start testing I clear the cache, but I get this error. My browser is Brave, it wasn't in the drop-down list

**Comment by kenodressel** [comment]
Ah okay, so i could reproduce your issue with chrome, until i cleared the cache once, then it was working fine for me again.

**Comment by kenodressel** [comment]
Do you observe a similar behavior or does it persist for you even after the cleared cache?

**Comment by Liubov-crypto** [comment]
> Do you observe a similar behavior or does it persist for you even after the cleared cache?

It persists after clearing the cache. Dex can stay on the mainnet for a long time, and then spontaneously switch to the testnet

**Comment by Liubov-crypto** [comment]
For me, this error is still reproduced: 
![err](https://user-images.githubusercontent.com/69896204/182390160-468125c3-02c6-4287-b573-89fdca7e58ea.png)

https://user-images.githubusercontent.com/69896204/182390187-7c120636-b8bc-4e6e-a712-f59df820e3c5.mov

**Comment by CedrikNikita** [comment]
https://github.com/aeternity/dex-ui/pull/440#issuecomment-1205041310
