### ISSUE TITLE
Network switch is not recognized by the aepp anymore

### ISSUE THREAD

**Issue by kenodressel** [aeternity/dex-ui#487]
### What happened?

Switching the network in the wallet has no effect on the dex

### How can we reproduce it?

1. login with superhero wallet extension
2. switch network
3. observe change in the wallet but not in the dex

### Which device did this issue occur on?

Desktop

### What browsers are you seeing the problem on?

Firefox

**Comment by bogdan-manole** [comment]
i can't reproduce the issue anymore

![Image](https://user-images.githubusercontent.com/3176255/226114054-04b2bfcc-52dd-4df7-9ae5-d97bdc639914.gif)
